# Generated by Django 4.2.1 on 2024-08-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0010_rename_status_file_saveconflictstxt_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('data', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('category', models.IntegerField()),
            ],
        ),
    ]
