# Generated by Django 4.2.1 on 2024-08-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0011_controllermanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllermanagement',
            name='data',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='controllermanagement',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
