# Generated by Django 4.2.1 on 2024-08-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0012_alter_controllermanagement_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllermanagement',
            name='num_visible_hosts',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
